/**
 * TypeScript interfaces for Role Generation
 * 
 * These interfaces define the structure of data generated by AI
 * and used for database insertion operations.
 */

// Base interfaces matching database schema
export interface RoleConfig {
  role_name: string;
  slug: string;
  description: string;
  core_skill: string;
  frameworks: string[];
  status: 'published' | 'draft';
}

export interface CertificateConfig {
  name: string;
  short_name: string;
  cert_id_prefix: string;
  type: 'default' | 'secondary' | 'ai';
  order_index: number;
  preview_image: string;
  description: string;
  certificate_name: string;
  price: number;
  original_price: number;
  badge: string;
  skill_frameworks: string[];
}

export interface AssessmentConfig {
  name: string;
  status: 'published' | 'draft';
}

export interface PhaseConfig {
  order_index: number;
  name: string;
  description: string;
}

export interface VisualModel {
  svg: string;
  name: string;
  description: string;
}

export interface ProjectMandate {
  initial_budget: string;
  high_level_goal: string;
  business_problem: string;
}

export interface ScenarioConfig {
  name: string;
  principle: string;
  context: string;
  challenge: string;
  task: string;
  key_concepts: string[];
  visual_model: VisualModel;
  status: 'published' | 'draft';
  difficulty: 'easy' | 'medium' | 'hard';
  skill_name: string;
  project_mandate: ProjectMandate;
}

export interface QuestionOption {
  text: string;
  option_id: 'A' | 'B' | 'C' | 'D';
  is_correct: boolean;
}

export interface QuestionConfig {
  scenario_index: number;
  question_text: string;
  options: QuestionOption[];
}

export interface ScorecardStat {
  skill: string;
  percentage: number;
}

export interface LandingPageContent {
  scorecard_stats: ScorecardStat[];
}

export interface LandingPageConfig {
  slug: string;
  hero_title: string;
  hero_description: string;
  content: LandingPageContent;
  meta_title: string;
  meta_description: string;
  keywords: string;
}

// Main generated role data interface
export interface GeneratedRoleData {
  role: RoleConfig;
  certificates: CertificateConfig[];
  assessment: AssessmentConfig;
  phases: PhaseConfig[];
  scenarios: ScenarioConfig[];
  questions: QuestionConfig[];
  landingPage: LandingPageConfig;
}

// Database insertion interfaces with IDs
export interface DatabaseRole extends RoleConfig {
  id?: number;
}

export interface DatabaseCertificate extends CertificateConfig {
  id?: number;
  role_id: number;
}

export interface DatabaseAssessment extends AssessmentConfig {
  id?: number;
  role_id: number;
}

export interface DatabasePhase extends PhaseConfig {
  id?: number;
  assessment_id: number;
  scenario_id?: number;
}

export interface DatabaseScenario extends ScenarioConfig {
  id?: number;
  role_id: number;
}

export interface DatabaseQuestion {
  id?: number;
  scenario_id: number;
  question_text: string;
  options: QuestionOption[];
}

export interface DatabaseLandingPage extends LandingPageConfig {
  id?: number;
  role_id: number;
}

// Validation result interfaces
export interface ValidationError {
  field: string;
  message: string;
  path?: string;
}

export interface ValidationResult {
  isValid: boolean;
  errors: ValidationError[];
  warnings?: string[];
}

// Progress tracking for database insertion
export interface InsertionProgress {
  step: 'role' | 'certificates' | 'assessment' | 'scenarios' | 'questions' | 'phases' | 'landing-page' | 'completed';
  message: string;
  success: boolean;
  error?: string;
}

export type InsertionProgressCallback = (progress: InsertionProgress) => void;

// Role management interfaces
export interface ExistingRole {
  id: number;
  role_name: string;
  slug: string;
  status: 'published' | 'draft';
  created_at: string;
  certificate_count?: number;
  scenario_count?: number;
  question_count?: number;
}

export interface RoleStats {
  total_roles: number;
  published_roles: number;
  total_certificates: number;
  total_scenarios: number;
  total_questions: number;
}

// API response interfaces
export interface RoleInsertionResult {
  success: boolean;
  role_id?: number;
  error?: string;
  progress?: InsertionProgress[];
}

export interface RoleDeletionResult {
  success: boolean;
  deleted_components: {
    certificates: number;
    scenarios: number;
    questions: number;
    phases: number;
    landing_page: boolean;
    role: boolean;
  };
  error?: string;
}

// Form state interfaces
export interface RoleGeneratorFormState {
  roleName: string;
  isGeneratingPrompt: boolean;
  generatedPrompt: string;
  jsonInput: string;
  isValidatingJson: boolean;
  validationResult: ValidationResult | null;
  isInsertingData: boolean;
  insertionProgress: InsertionProgress[];
  lastInsertionResult: RoleInsertionResult | null;
}

// Constants for validation
export const REQUIRED_CERTIFICATE_COUNT = 5;
export const REQUIRED_SCENARIO_COUNT = 5;
export const REQUIRED_QUESTION_COUNT = 25;
export const QUESTIONS_PER_SCENARIO = 5;
export const REQUIRED_SCORECARD_STATS = 5;

export const CERTIFICATE_TYPES = ['default', 'secondary', 'ai'] as const;
export const DIFFICULTY_LEVELS = ['easy', 'medium', 'hard'] as const;
export const STATUS_OPTIONS = ['published', 'draft'] as const;
export const QUESTION_OPTIONS = ['A', 'B', 'C', 'D'] as const;

// Pricing tiers (for validation)
export const PRICING_TIERS = {
  default_1: { price: 99, original: 299 },
  default_2: { price: 149, original: 349 },
  secondary_1: { price: 129, original: 329 },
  secondary_2: { price: 119, original: 319 },
  ai: { price: 159, original: 359 }
} as const;